/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.Brands_BUS;
import BUS.Cars_BUS;
import BUS.Locations_BUS;
import BUS.Booking_BUS;
import DTO.Locations_DTO;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author ADMIN
 */
public class BookCars_GUI extends javax.swing.JFrame {

    /**
     * Creates new form BookCars_GUI
     */
    Border border = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 0, 153));
    Border panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.darkGray);
    Brands_BUS brandBus = new Brands_BUS();
    Cars_BUS carsBus = new Cars_BUS();
    Locations_BUS locationBus = new Locations_BUS();
    Booking_BUS bookingBus = new Booking_BUS();
    HashMap<Integer, String> map = brandBus.getBrandsHashMap();
    public BookCars_GUI() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
        
        jLabel_selectcar.setBorder(border);
        jLabel_pickup.setBorder(border);
        jLabel_selectcustomer.setBorder(border);
        jLabel_dropoff.setBorder(border);
        
        jPanel_selectcar.setBorder(panel_border);
        jPanel_pickup.setBorder(panel_border);
        jPanel_selectcustomer.setBorder(panel_border);
        jPanel_dropoff.setBorder(panel_border);
        
        populateComboboxBrands();
    }

    // create a function to populate the jcombobox_brands with brands
    // and to do that we will use a hashmap
    public void populateComboboxAddress(String pickup_or_dropoff, String city) {
        if (pickup_or_dropoff.equals("pickup")){
            //clear combobox
                jComboBox_PickUp_Address.removeAllItems();
            //populate combobox
            for (Locations_DTO l : locationBus.locationsListByCity(city))
            {
                jComboBox_PickUp_Address.addItem(l.getAddress());
            }
        } 
        else if (pickup_or_dropoff.equals("dropoff")){
            //clear combobox
                jComboBox_DropOff_Address.removeAllItems();
            //populate combobox
            for (Locations_DTO l : locationBus.locationsListByCity(city))
            {
                jComboBox_DropOff_Address.addItem(l.getAddress());
            }
        } 
    }
    
    public void populateComboboxBrands() {
        for (String s : map.values()) {
            jComboBox_Brands.addItem(s);
        }
    }
    
    // create a static function to display customer id and name
    public static void displayCustomer (String id, String name)
    {
        jTextField_customer.setText(name);
        jLabel_customer_id.setText(id);
    }
    
    public static void displayCarInfo(String id, String model, String price)
    {
        jLabel_car_id.setText(id);
        jLabel_car_model.setText(model);
        jLabel_price_car.setText(price);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_timetable = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel_selectcar = new javax.swing.JPanel();
        jLabel_selectcar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_Brands = new javax.swing.JComboBox<>();
        jButton_selectcar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel_brand_id = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel_car_id = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel_car_model = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel_price_car = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel_selectcustomer = new javax.swing.JPanel();
        jLabel_selectcustomer = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_customer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel_customer_id = new javax.swing.JLabel();
        jButton_selectcustomer = new javax.swing.JButton();
        jPanel_pickup = new javax.swing.JPanel();
        jLabel_pickup = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_PickUp_City = new javax.swing.JComboBox<>();
        jComboBox_PickUp_Address = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser_PickUp_Date = new com.toedter.calendar.JDateChooser();
        timePicker_PickUp_Time = new com.github.lgooddatepicker.components.TimePicker();
        jPanel_dropoff = new javax.swing.JPanel();
        jLabel_dropoff = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox_DropOff_City = new javax.swing.JComboBox<>();
        jComboBox_DropOff_Address = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser_DropOff_Date = new com.toedter.calendar.JDateChooser();
        timePicker_DropOff_Time = new com.github.lgooddatepicker.components.TimePicker();
        jButton_bookinglist = new javax.swing.JButton();
        jButton_bookthiscar = new javax.swing.JButton();
        jButton_edit_remove = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel_price_text = new javax.swing.JLabel();
        jLabel_total_price = new javax.swing.JLabel();
        jButton_calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Book a Car");
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_timetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timetable.png"))); // NOI18N

        jLabel_close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_timetable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_timetable, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_selectcar.setBackground(new java.awt.Color(72, 219, 251));

        jLabel_selectcar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_selectcar.setText("Select a Car");
        jLabel_selectcar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_selectcar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Brand:");
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Car:");
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox_Brands.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBox_Brands.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_Brands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_BrandsActionPerformed(evt);
            }
        });

        jButton_selectcar.setText("Select Car");
        jButton_selectcar.setBackground(new java.awt.Color(0, 0, 153));
        jButton_selectcar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_selectcar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_selectcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectcarActionPerformed(evt);
            }
        });

        jLabel11.setText("ID:");
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_brand_id.setText("000");
        jLabel_brand_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_brand_id.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("ID:");
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_car_id.setText("000");
        jLabel_car_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_car_id.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setText("Model:");
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_car_model.setText("###");
        jLabel_car_model.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_car_model.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Price:");
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_price_car.setText("000");
        jLabel_price_car.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_price_car.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setText("|");
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel_selectcarLayout = new javax.swing.GroupLayout(jPanel_selectcar);
        jPanel_selectcar.setLayout(jPanel_selectcarLayout);
        jPanel_selectcarLayout.setHorizontalGroup(
            jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_selectcar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
            .addGroup(jPanel_selectcarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_selectcarLayout.createSequentialGroup()
                        .addComponent(jComboBox_Brands, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_brand_id))
                    .addGroup(jPanel_selectcarLayout.createSequentialGroup()
                        .addComponent(jButton_selectcar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_selectcarLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_car_model))
                            .addGroup(jPanel_selectcarLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_car_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_price_car)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel_selectcarLayout.setVerticalGroup(
            jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectcarLayout.createSequentialGroup()
                .addComponent(jLabel_selectcar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel_brand_id))
                    .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jComboBox_Brands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel_price_car))
                    .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel_car_id)
                        .addComponent(jLabel23))
                    .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jButton_selectcar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_selectcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel_car_model))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_selectcustomer.setBackground(new java.awt.Color(72, 219, 251));

        jLabel_selectcustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_selectcustomer.setText("Select Customer");
        jLabel_selectcustomer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_selectcustomer.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("ID:");
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        jTextField_customer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_customerMouseClicked(evt);
            }
        });

        jLabel10.setText("Customer:");
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_customer_id.setText("000");
        jLabel_customer_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer_id.setForeground(new java.awt.Color(255, 255, 255));

        jButton_selectcustomer.setText("Select Customer");
        jButton_selectcustomer.setBackground(new java.awt.Color(0, 0, 153));
        jButton_selectcustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_selectcustomer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_selectcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectcustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_selectcustomerLayout = new javax.swing.GroupLayout(jPanel_selectcustomer);
        jPanel_selectcustomer.setLayout(jPanel_selectcustomerLayout);
        jPanel_selectcustomerLayout.setHorizontalGroup(
            jPanel_selectcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_selectcustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
            .addGroup(jPanel_selectcustomerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_selectcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_selectcustomerLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_customer_id)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_selectcustomerLayout.createSequentialGroup()
                        .addComponent(jTextField_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_selectcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_selectcustomerLayout.setVerticalGroup(
            jPanel_selectcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectcustomerLayout.createSequentialGroup()
                .addComponent(jLabel_selectcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel_selectcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_selectcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jButton_selectcustomer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel_selectcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_customer_id))
                .addGap(21, 21, 21))
        );

        jPanel_pickup.setBackground(new java.awt.Color(72, 219, 251));

        jLabel_pickup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_pickup.setText("Pick Up Location & Date");
        jLabel_pickup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_pickup.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Province:");
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Address:");
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox_PickUp_City.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa-Vũng Tàu", "Bạc Liêu", "Bắc Giang", "Bắc Kạn", "Bắc Ninh", "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước", "Bình Thuận", "Cà Mau", "Cao Bằng", "Cần Thơ", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lạng Sơn", "Lào Cai", "Lâm Đồng", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế\t", "Tiền Giang", "TP. Hồ Chí Minh", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));
        jComboBox_PickUp_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PickUp_CityActionPerformed(evt);
            }
        });

        jComboBox_PickUp_Address.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel14.setText("Date:");
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Time:");
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_pickupLayout = new javax.swing.GroupLayout(jPanel_pickup);
        jPanel_pickup.setLayout(jPanel_pickupLayout);
        jPanel_pickupLayout.setHorizontalGroup(
            jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_pickup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addGroup(jPanel_pickupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_PickUp_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timePicker_PickUp_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_PickUp_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_PickUp_City, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_pickupLayout.setVerticalGroup(
            jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pickupLayout.createSequentialGroup()
                .addComponent(jLabel_pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox_PickUp_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_PickUp_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jDateChooser_PickUp_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timePicker_PickUp_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel_dropoff.setBackground(new java.awt.Color(72, 219, 251));

        jLabel_dropoff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_dropoff.setText("Drop Off Location & Date");
        jLabel_dropoff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_dropoff.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Province:");
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Address:");
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox_DropOff_City.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa-Vũng Tàu", "Bạc Liêu", "Bắc Giang", "Bắc Kạn", "Bắc Ninh", "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước", "Bình Thuận", "Cà Mau", "Cao Bằng", "Cần Thơ", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lạng Sơn", "Lào Cai", "Lâm Đồng", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế\t", "Tiền Giang", "TP. Hồ Chí Minh", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));
        jComboBox_DropOff_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DropOff_CityActionPerformed(evt);
            }
        });

        jComboBox_DropOff_Address.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel19.setText("Date:");
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setText("Time:");
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_dropoffLayout = new javax.swing.GroupLayout(jPanel_dropoff);
        jPanel_dropoff.setLayout(jPanel_dropoffLayout);
        jPanel_dropoffLayout.setHorizontalGroup(
            jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_dropoff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addGroup(jPanel_dropoffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_DropOff_City, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_DropOff_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_DropOff_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timePicker_DropOff_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_dropoffLayout.setVerticalGroup(
            jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dropoffLayout.createSequentialGroup()
                .addComponent(jLabel_dropoff, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox_DropOff_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_DropOff_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jDateChooser_DropOff_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timePicker_DropOff_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButton_bookinglist.setText("Booking List");
        jButton_bookinglist.setBackground(new java.awt.Color(255, 0, 255));
        jButton_bookinglist.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_bookinglist.setForeground(new java.awt.Color(255, 255, 255));
        jButton_bookinglist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookinglistActionPerformed(evt);
            }
        });

        jButton_bookthiscar.setText("Book This Car");
        jButton_bookthiscar.setBackground(new java.awt.Color(0, 0, 153));
        jButton_bookthiscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_bookthiscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_bookthiscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookthiscarActionPerformed(evt);
            }
        });

        jButton_edit_remove.setText("Edit/Remove Booking");
        jButton_edit_remove.setBackground(new java.awt.Color(255, 153, 0));
        jButton_edit_remove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_edit_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_removeActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_price_text.setText("Total Price:");
        jLabel_price_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel_total_price.setText("0000");
        jLabel_total_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton_calculate.setText("calculate");
        jButton_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel_price_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_calculate)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_price_text)
                    .addComponent(jLabel_total_price)
                    .addComponent(jButton_calculate))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel_selectcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_selectcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_edit_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_bookinglist, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_bookthiscar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_dropoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_pickup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_pickup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_selectcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_dropoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel_selectcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_bookinglist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_bookthiscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_edit_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();

    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jButton_selectcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectcustomerActionPerformed
        //show the customer list
        CustomersList_GUI cstl_gui = new CustomersList_GUI("add");
        cstl_gui.setVisible(true);
    }//GEN-LAST:event_jButton_selectcustomerActionPerformed

    private void jButton_selectcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectcarActionPerformed
        //get the brand id
        int brand_id = Integer.valueOf(jLabel_brand_id.getText());
        
        CarsListByBrand_GUI carslbr_gui = new CarsListByBrand_GUI(brand_id, "add");
        carslbr_gui.setVisible(true);
    }//GEN-LAST:event_jButton_selectcarActionPerformed

    private void jButton_bookinglistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bookinglistActionPerformed
        BookingList_GUI bkl_gui = new BookingList_GUI("add");
        bkl_gui.setVisible(true);
    }//GEN-LAST:event_jButton_bookinglistActionPerformed

    private void jButton_bookthiscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bookthiscarActionPerformed
        // add a new booking
        try{
            // get the car info
            int car_id = Integer.valueOf(jLabel_car_id.getText());
            // get the customer info
            int customer_id = Integer.valueOf(jLabel_customer_id.getText());
            // get the pick up info
            String pickup_city = jComboBox_PickUp_City.getSelectedItem().toString();
            String pickup_address = jComboBox_PickUp_Address.getSelectedItem().toString();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String pickup_date = dateFormat.format(jDateChooser_PickUp_Date.getDate());
            Date pickup_date_ = dateFormat.parse(pickup_date);
            String pickup_time = timePicker_PickUp_Time.getText();

            // get the dropoff info
            String dropoff_city = jComboBox_DropOff_City.getSelectedItem().toString();
            String dropoff_address = jComboBox_DropOff_Address.getSelectedItem().toString();

            String dropoff_date = dateFormat.format(jDateChooser_DropOff_Date.getDate());
            Date dropoff_date_ = dateFormat.parse(dropoff_date);
            String dropoff_time = timePicker_DropOff_Time.getText();
            
            // get date difference in days
            long diff = dropoff_date_.getTime() - pickup_date_.getTime();
            //System.out.println("diff - " + diff); 
            
            int diff_days = (int) (diff / 1000/ 60/ 60/ 24); 
            //System.out.println("diff_days - " + diff_days);
            
            int price = Integer.valueOf(jLabel_price_car.getText());
            int total_price = diff_days * price;

            jLabel_price_text.setText("Total Price (" + String.valueOf(price) + " x " + String.valueOf(diff_days) +"):");
            jLabel_total_price.setText(String.valueOf(total_price));
            //check if the dropoff date is before the pickup date
            if(dropoff_date_.before(pickup_date_))
            {
                JOptionPane.showMessageDialog(null, "The Drop Off Date Must Be After The Pickup Date", "Invalid Date", 2);
            }
            //check if the dropoff date is equal to the pickup date
            else if(dropoff_date_.equals(pickup_date_))
            {
                //check if the dropoff date is before the pickup time
                if(timePicker_DropOff_Time.getTime().isBefore(timePicker_PickUp_Time.getTime()))
                {
                    JOptionPane.showMessageDialog(null, "The Drop Off Time Must Be After The Pickup Time", "Invalid Time", 2);
                }
                else
                {
                    // if it's the same day in different pickup and drop off time
                    // we will count it as 1H
                    total_price = 1 * price;
                    jLabel_price_text.setText("Total Price (" + String.valueOf(price) + " x " + String.valueOf(1) +"):");
                    jLabel_total_price.setText(String.valueOf(total_price));
                    bookingBus.addNewBooking(car_id, customer_id, pickup_city, pickup_address, pickup_date, pickup_time, dropoff_city, dropoff_address, dropoff_date, dropoff_time, total_price);
                }
            }
            else
            {
                bookingBus.addNewBooking(car_id, customer_id, pickup_city, pickup_address, pickup_date, pickup_time, dropoff_city, dropoff_address, dropoff_date, dropoff_time, total_price);
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Enter Valid Data - Make Sure To Enter All The Information", "Invalid Info", 2);
        }
    }//GEN-LAST:event_jButton_bookthiscarActionPerformed

    private void jButton_edit_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_removeActionPerformed
        Booking_Edit_Remove_GUI bker_gui = new Booking_Edit_Remove_GUI();
        bker_gui.setVisible(true);
    }//GEN-LAST:event_jButton_edit_removeActionPerformed

    private void jComboBox_BrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_BrandsActionPerformed
        //get the selected brand id
        int brand_id = 0;
        for (Map.Entry<Integer, String> entry : map.entrySet())
        {
            if (entry.getValue().equals(jComboBox_Brands.getSelectedItem().toString()))
            {
                brand_id = entry.getKey();
            }
        }
        jLabel_brand_id.setText(String.valueOf(brand_id));
    }//GEN-LAST:event_jComboBox_BrandsActionPerformed

    private void jComboBox_PickUp_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PickUp_CityActionPerformed
        // populate jComboBox address depending on the city combobox
        populateComboboxAddress("pickup", jComboBox_PickUp_City.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox_PickUp_CityActionPerformed

    private void jComboBox_DropOff_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DropOff_CityActionPerformed
        // populate jComboBox address depending on the city combobox
        populateComboboxAddress("dropoff", jComboBox_DropOff_City.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox_DropOff_CityActionPerformed

    private void jButton_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculateActionPerformed
        try {
            // calculate the total price
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String pickup_date = dateFormat.format(jDateChooser_PickUp_Date.getDate());
            Date pickup_date_ = dateFormat.parse(pickup_date);
            //String pickup_time = timePicker_PickUp_Time.getText();
            
            String dropoff_date = dateFormat.format(jDateChooser_DropOff_Date.getDate());
            Date dropoff_date_ = dateFormat.parse(dropoff_date);
            //String dropoff_time = timePicker_DropOff_Time.getText();
            
            long diff = dropoff_date_.getTime() - pickup_date_.getTime();
            //System.out.println("diff - " + diff);
            
            int diff_days = (int) (diff / 1000/ 60/ 60/ 24);
            //System.out.println("diff_days - " + diff_days);
            
            int price = Integer.valueOf(jLabel_price_car.getText());
            int total_price = diff_days * price;
            
            jLabel_price_text.setText("Total Price (" + String.valueOf(price) + " x " + String.valueOf(diff_days) +"):");
            jLabel_total_price.setText(String.valueOf(total_price));
            //check if the dropoff date is before the pickup date
            if(dropoff_date_.before(pickup_date_))
            {
                JOptionPane.showMessageDialog(null, "The Drop Off Date Must Be After The Pickup Date", "Invalid Date", 2);
            }
            //check if the dropoff date is equal to the pickup date
            else if(dropoff_date_.equals(pickup_date_))
            {
                //check if the dropoff date is before the pickup time
                if(timePicker_DropOff_Time.getTime().isBefore(timePicker_PickUp_Time.getTime()))
                {
                    JOptionPane.showMessageDialog(null, "The Drop Off Time Must Be After The Pickup Time", "Invalid Time", 2);
                }
                else
                {
                    // if it's the same day in different pickup and drop off time
                    // we will count it as 1H
                    total_price = 1 * price;
                    jLabel_price_text.setText("Total Price (" + String.valueOf(price) + " x " + String.valueOf(1) +"):");
                    jLabel_total_price.setText(String.valueOf(total_price));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "You Need To Select a Car and Pickup/Drop Date", "Invalid Info", 2);
        }
    }//GEN-LAST:event_jButton_calculateActionPerformed

    private void jTextField_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_customerMouseClicked

    }//GEN-LAST:event_jTextField_customerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookCars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookCars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookCars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookCars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookCars_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_bookinglist;
    private javax.swing.JButton jButton_bookthiscar;
    private javax.swing.JButton jButton_calculate;
    private javax.swing.JButton jButton_edit_remove;
    private javax.swing.JButton jButton_selectcar;
    private javax.swing.JButton jButton_selectcustomer;
    private javax.swing.JComboBox<String> jComboBox_Brands;
    private javax.swing.JComboBox<String> jComboBox_DropOff_Address;
    private javax.swing.JComboBox<String> jComboBox_DropOff_City;
    private javax.swing.JComboBox<String> jComboBox_PickUp_Address;
    private javax.swing.JComboBox<String> jComboBox_PickUp_City;
    private com.toedter.calendar.JDateChooser jDateChooser_DropOff_Date;
    private com.toedter.calendar.JDateChooser jDateChooser_PickUp_Date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JLabel jLabel_brand_id;
    private static javax.swing.JLabel jLabel_car_id;
    private static javax.swing.JLabel jLabel_car_model;
    private javax.swing.JLabel jLabel_close;
    private static javax.swing.JLabel jLabel_customer_id;
    private javax.swing.JLabel jLabel_dropoff;
    private javax.swing.JLabel jLabel_pickup;
    private static javax.swing.JLabel jLabel_price_car;
    private javax.swing.JLabel jLabel_price_text;
    private javax.swing.JLabel jLabel_selectcar;
    private javax.swing.JLabel jLabel_selectcustomer;
    private javax.swing.JLabel jLabel_timetable;
    private static javax.swing.JLabel jLabel_total_price;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_dropoff;
    private javax.swing.JPanel jPanel_pickup;
    private javax.swing.JPanel jPanel_selectcar;
    private javax.swing.JPanel jPanel_selectcustomer;
    private static javax.swing.JTextField jTextField_customer;
    private com.github.lgooddatepicker.components.TimePicker timePicker_DropOff_Time;
    private com.github.lgooddatepicker.components.TimePicker timePicker_PickUp_Time;
    // End of variables declaration//GEN-END:variables
}
