/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CarImage_BUS;
import BUS.Cars_BUS;
import DTO.CarImage_DTO;
import DTO.Cars_DTO;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class CarImages_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CarsImages_GUI
     */
    Cars_BUS carsBus = new Cars_BUS();
    ArrayList<Cars_DTO> cars_list = carsBus.getAllCars();
    
    CarImage_BUS carsimageBus = new CarImage_BUS();
    ArrayList<CarImage_DTO> carsimage_list;
    
    public CarImages_GUI() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
        
        populateJTableWithCars();
        
        jLabel_CarImage.setPreferredSize(new Dimension(205, 152));
        jLabel_CarImage.setMinimumSize(new Dimension(205, 152));
        jLabel_CarImage.setMaximumSize(new Dimension(205, 152));
    }

    public void displayImage (int width, int height, String image_path, JLabel label)
    {
        ImageIcon imageIco = new ImageIcon(image_path);
        Image image = imageIco.getImage().getScaledInstance(205, 152, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(image));
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
    }
    
    public void displayByteImage (int width, int height, byte[] image_byte, JLabel label)
    {
        ImageIcon imageIco = new ImageIcon(image_byte);
        Image image = imageIco.getImage().getScaledInstance(205, 152, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(image));
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
    }
    
    public String selectImage()
    {
        JFileChooser fileChooser = new JFileChooser(); 
        fileChooser.setDialogTitle("Select Pricture");
        
        fileChooser.setCurrentDirectory (new File("D:\\Nosql\\CarsRentalManagementStore\\CarsRentalManagementStore\\src\\images\\car"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("image", ".png",".jpg"); 
        fileChooser.addChoosableFileFilter(filter);
        
        int state = fileChooser.showSaveDialog (null);
        String path = ""; 
        if (state == JFileChooser.APPROVE_OPTION)
        {
            path = fileChooser.getSelectedFile().getAbsolutePath();
        }
        return path;
    }
    
    public void populateJTableWithCars() {
        //jtable columns
        String[] columnsName = {"ID", "Model", "Class"};
        
        // jtable rows
        Object[][] rows = new Object[cars_list.size()][columnsName.length];
        
        for(int i=0; i < cars_list.size(); i++)
        {
            rows[i][0] = cars_list.get(i).getCar_id();
            rows[i][1] = cars_list.get(i).getModel();
            rows[i][2] = cars_list.get(i).getClass_();
        }
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        jTable_Cars.setModel(model);
    }
    
    public void populateJTableWithCarImages(int car_id) {
        carsimage_list = carsimageBus.carImagesList(car_id);
        //jtable columns
        String[] columnsName = {"Image ID"};
        
        // jtable rows
        Object[][] rows = new Object[carsimage_list.size()][columnsName.length];
        
        for(int i=0; i < carsimage_list.size(); i++)
        {
            rows[i][0] = carsimage_list.get(i).getImg_id();
        }
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        jTable_CarImages.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_cars_image = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_CarImages = new javax.swing.JTable();
        jLabel_CarImage = new javax.swing.JLabel();
        jButton_Select_Image = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cars = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Remove_Image = new javax.swing.JButton();
        jButton_Add_Image = new javax.swing.JButton();
        jButton_Images_Slider = new javax.swing.JButton();
        jLabel_imagePath = new javax.swing.JLabel();
        jButton_Undo_Image = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Car Images");

        jLabel_cars_image.setBackground(new java.awt.Color(255, 204, 0));
        jLabel_cars_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_two.png"))); // NOI18N
        jLabel_cars_image.setOpaque(true);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_cars_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_cars_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable_CarImages.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable_CarImages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_CarImages.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable_CarImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CarImagesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_CarImages);
        jTable_CarImages.setCellSelectionEnabled(false);
        jTable_CarImages.setRowSelectionAllowed(true);
        jTable_CarImages.setColumnSelectionAllowed(false);
        jTable_CarImages.setDefaultEditor(Object.class, null);

        jLabel_CarImage.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_CarImage.setOpaque(true);

        jButton_Select_Image.setBackground(new java.awt.Color(0, 102, 204));
        jButton_Select_Image.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Select_Image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Select_Image.setText("Select Image");
        jButton_Select_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_ImageActionPerformed(evt);
            }
        });

        jTable_Cars.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable_Cars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Cars.setRowHeight(50);
        jTable_Cars.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable_Cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CarsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Cars);
        jTable_Cars.setCellSelectionEnabled(false);
        jTable_Cars.setRowSelectionAllowed(true);
        jTable_Cars.setColumnSelectionAllowed(false);
        jTable_Cars.setDefaultEditor(Object.class, null);

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel1.setText("Cars");

        jLabel2.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel2.setText("Selected Car Images");

        jButton_Remove_Image.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Remove_Image.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Remove_Image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Image.setText("Remove Image");
        jButton_Remove_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_ImageActionPerformed(evt);
            }
        });

        jButton_Add_Image.setBackground(new java.awt.Color(102, 255, 102));
        jButton_Add_Image.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Add_Image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Image.setText("Add Image");
        jButton_Add_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ImageActionPerformed(evt);
            }
        });

        jButton_Images_Slider.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Images_Slider.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Images_Slider.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Images_Slider.setText("Images Slider");
        jButton_Images_Slider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Images_SliderActionPerformed(evt);
            }
        });

        jLabel_imagePath.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_imagePath.setText("##############");

        jButton_Undo_Image.setBackground(new java.awt.Color(204, 51, 255));
        jButton_Undo_Image.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Undo_Image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Undo_Image.setText("Undo Image");
        jButton_Undo_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Undo_ImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_CarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Select_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Add_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Images_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Remove_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Undo_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_CarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Select_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Add_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Remove_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Images_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Undo_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jTable_CarImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CarImagesMouseClicked
        //display the selected image
        // get image id from the jtable
        int index = jTable_CarImages.getSelectedRow();
        //System.out.println("index ->" + index);
        int image_id = Integer.valueOf(jTable_CarImages.getValueAt(index, 0).toString());
        //System.out.println("image_id -> " + image_id);
        
        byte[] img = null;
        for (CarImage_DTO cimg: carsimage_list)
        {
            if(cimg.getImg_id() == image_id)
            {
                img = cimg.getCar_img();
            }
        }
        displayByteImage(jTable_CarImages.getWidth(), jTable_CarImages.getHeight(), img, jLabel_CarImage);
    }//GEN-LAST:event_jTable_CarImagesMouseClicked

    private void jTable_CarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CarsMouseClicked
        // get the selected brand logo
        int index = jTable_Cars.getSelectedRow();
        int car_id = Integer.valueOf(jTable_Cars.getValueAt(index, 0).toString());
//        System.out.println(id);

        populateJTableWithCarImages(car_id);
        carsimage_list = carsimageBus.carImagesList(car_id);
    }//GEN-LAST:event_jTable_CarsMouseClicked

    private void jButton_Select_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_ImageActionPerformed
        //browse and display images
        String imagePath = selectImage();
        displayImage(jLabel_CarImage.getWidth(), jLabel_CarImage.getHeight(), imagePath, jLabel_CarImage);
        jLabel_imagePath.setText(imagePath);
    }//GEN-LAST:event_jButton_Select_ImageActionPerformed

    private void jButton_Add_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ImageActionPerformed
        try{
            int index = jTable_Cars.getSelectedRow();
            int car_id = Integer.valueOf(jTable_Cars.getValueAt(index, 0).toString());
            byte[] car_image = Files.readAllBytes(Paths.get(jLabel_imagePath.getText()));
            
            System.out.println(car_id);
            carsimageBus.addCarImage(car_id, car_image);
            populateJTableWithCarImages(car_id);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Select An Image [ " + ex.getMessage()+" ]" , "Car Image", 2);
            //Logger.getLogger(CarImages_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Add_ImageActionPerformed

    private void jButton_Remove_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_ImageActionPerformed
        try{
            int index = jTable_CarImages.getSelectedRow();
            int image_id = Integer.valueOf(jTable_CarImages.getValueAt(index, 0).toString());
        
            int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Delete this Image?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION){
                carsimageBus.removeCarImage(image_id);
                jTable_CarsMouseClicked(null);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Select the Image First", "Delete Image", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_Remove_ImageActionPerformed

    private void jButton_Images_SliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Images_SliderActionPerformed
        try {
            int index = jTable_Cars.getSelectedRow();
            int carimage_id = Integer.valueOf(jTable_Cars.getValueAt(index, 0).toString()); //car id
            try{
                CarImages_Slider_GUI slider_gui = new CarImages_Slider_GUI(carimage_id);
                slider_gui.setVisible(true);
            } catch(Exception ex){
                JOptionPane.showMessageDialog(null, "This Car Has No Images", "No Image", 2);
            }
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, "You Need to Select the Car First", "Error", 2);
        }
    }//GEN-LAST:event_jButton_Images_SliderActionPerformed

    private void jButton_Undo_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Undo_ImageActionPerformed
        try {
            int index = jTable_Cars.getSelectedRow(); 
            if (index != -1) { 
                int car_id = Integer.valueOf(jTable_Cars.getValueAt(index, 0).toString()); 
                carsimageBus.undoRemoveCarImage(); 
                populateJTableWithCarImages(car_id); 
                populateJTableWithCars();
            } else {
                JOptionPane.showMessageDialog(this, "Bạn cần chọn xe trước!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_Undo_ImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarImages_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarImages_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarImages_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarImages_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarImages_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Image;
    private javax.swing.JButton jButton_Images_Slider;
    private javax.swing.JButton jButton_Remove_Image;
    private javax.swing.JButton jButton_Select_Image;
    private javax.swing.JButton jButton_Undo_Image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_CarImage;
    private javax.swing.JLabel jLabel_cars_image;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_imagePath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_CarImages;
    private javax.swing.JTable jTable_Cars;
    // End of variables declaration//GEN-END:variables
}
