/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.Cars_BUS;
import BUS.Brands_BUS;
import DTO.Cars_DTO;
import DAO.Cars_DAO;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author ADMIN
 */
public class Cars_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Cars_GUI
     */
    
    Cars_BUS carsBus = new Cars_BUS();
    Brands_BUS brandBus = new Brands_BUS();
    HashMap<Integer, String> map = brandBus.getBrandsHashMap();
    
    public Cars_GUI() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        ButtonGroup btn_group = new ButtonGroup();
        btn_group.add(jRadioButton_Automatic);
        btn_group.add(jRadioButton_Manual);
        
        populateComboboxBrands();
        
    }

    public void populateComboboxBrands() {
        for (String s : map.values()) {
            jComboBox_brand.addItem(s);
        }
    }
    
    private boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public boolean verify() {
        String model = jTextField_Model.getText();
        String _class_ = jTextField_Class.getText();
        String brandIdText = jLabel_brand_id.getText();
        int id = (int) jSpinner_id.getValue();
        
        if (id == 0) {
           JOptionPane.showMessageDialog(null, "ID cannot be 0", "Invalid Info", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (brandIdText.equals("#") || !isNumeric(brandIdText)) {
            JOptionPane.showMessageDialog(null, "Select a valid brand", "Invalid Info", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (!model.trim().equals("") && !_class_.trim().equals("")) {
            if (!jRadioButton_Automatic.isSelected() && !jRadioButton_Manual.isSelected()) {
                JOptionPane.showMessageDialog(null, "Select a gearbox type (Automatic or Manual)", "Invalid Info", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Enter a Valid Model and Class", "Invalid Info", 2);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_cars = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_add_car = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jLabel_imagePath = new javax.swing.JLabel();
        jButton_reset = new javax.swing.JButton();
        jButton_addcarimages = new javax.swing.JButton();
        int max_3 = Integer.MAX_VALUE;
        int min_3 = 0;
        int step_3 = 1;
        int i_3 = 0;

        SpinnerModel spinner_model_3 = new SpinnerNumberModel(i_3, min_3, Integer.MAX_VALUE, step_3);
        jSpinner_id = new javax.swing.JSpinner(spinner_model_3);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox_Features_AirCond = new javax.swing.JCheckBox();
        jCheckBox_Features_Airbags = new javax.swing.JCheckBox();
        jCheckBox_Features_Sunroof = new javax.swing.JCheckBox();
        jCheckBox_Features_HeatedSeats = new javax.swing.JCheckBox();
        jCheckBox_Features_NavigationSystems = new javax.swing.JCheckBox();
        jCheckBox_Features_Bluetooth = new javax.swing.JCheckBox();
        jCheckBox_Features_ElectricWindows = new javax.swing.JCheckBox();
        jCheckBox_Features_GPS = new javax.swing.JCheckBox();
        jButton_brandslist = new javax.swing.JButton();
        jButton_carslist = new javax.swing.JButton();
        jTextField_Class = new javax.swing.JTextField();
        jComboBox_brand = new javax.swing.JComboBox<>();
        jComboBox_Fuel = new javax.swing.JComboBox<>();
        jComboBox_Color = new javax.swing.JComboBox<>();
        int max_2 = 20;
        int min_2 = 2;
        int step_2 = 1;
        int i_2 = 2;

        SpinnerModel spinner_model_2 = new SpinnerNumberModel(i_2, min_2, max_2, step_2);
        jSpinner_passengers = new javax.swing.JSpinner(spinner_model_2);
        jTextField_Model = new javax.swing.JTextField();
        int max = 10000;
        int min = 10;
        int step = 1;
        int i = 10;
        SpinnerModel spinner_model = new SpinnerNumberModel(i, min, max, step);
        jSpinner_price = new javax.swing.JSpinner(spinner_model);
        jRadioButton_Automatic = new javax.swing.JRadioButton();
        jRadioButton_Manual = new javax.swing.JRadioButton();
        jLabel_brand_id = new javax.swing.JLabel();
        jButton_search = new javax.swing.JButton();
        btn_undo_car = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cars");

        jLabel_cars.setBackground(new java.awt.Color(0, 51, 51));
        jLabel_cars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car.png"))); // NOI18N
        jLabel_cars.setOpaque(true);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_cars)
                .addGap(271, 271, 271)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_cars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Brand:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Model:");

        jButton_add_car.setBackground(new java.awt.Color(51, 255, 51));
        jButton_add_car.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_add_car.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_car.setText("Add");
        jButton_add_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_carActionPerformed(evt);
            }
        });

        jButton_edit.setBackground(new java.awt.Color(51, 51, 255));
        jButton_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_remove.setBackground(new java.awt.Color(255, 0, 0));
        jButton_remove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        jLabel_imagePath.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_reset.setBackground(new java.awt.Color(230, 126, 34));
        jButton_reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_reset.setText("Reset");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_addcarimages.setBackground(new java.awt.Color(153, 153, 0));
        jButton_addcarimages.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_addcarimages.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addcarimages.setText("Add Car Images");
        jButton_addcarimages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addcarimagesActionPerformed(evt);
            }
        });

        jSpinner_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Fuel:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Color:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Class:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("Features:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Passengers:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Price/day:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Gearbox:");

        jCheckBox_Features_AirCond.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_AirCond.setText("Air Conditioning");

        jCheckBox_Features_Airbags.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_Airbags.setText("Airbags");

        jCheckBox_Features_Sunroof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_Sunroof.setText("Sunroof");

        jCheckBox_Features_HeatedSeats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_HeatedSeats.setText("Heated Seats");

        jCheckBox_Features_NavigationSystems.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_NavigationSystems.setText("Navigation Systems");

        jCheckBox_Features_Bluetooth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_Bluetooth.setText("Bluetooth");

        jCheckBox_Features_ElectricWindows.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_ElectricWindows.setText("Electric Windows");

        jCheckBox_Features_GPS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_Features_GPS.setText("GPS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_Features_AirCond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_Features_Airbags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_Features_Sunroof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_Features_HeatedSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(112, 112, 112)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_Features_Bluetooth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_Features_NavigationSystems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_Features_ElectricWindows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_Features_GPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Features_AirCond)
                    .addComponent(jCheckBox_Features_Sunroof)
                    .addComponent(jCheckBox_Features_NavigationSystems)
                    .addComponent(jCheckBox_Features_ElectricWindows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Features_Airbags)
                    .addComponent(jCheckBox_Features_HeatedSeats)
                    .addComponent(jCheckBox_Features_Bluetooth)
                    .addComponent(jCheckBox_Features_GPS))
                .addGap(33, 33, 33))
        );

        jButton_brandslist.setBackground(new java.awt.Color(153, 153, 0));
        jButton_brandslist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_brandslist.setForeground(new java.awt.Color(255, 255, 255));
        jButton_brandslist.setText("Brands List ");
        jButton_brandslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_brandslistActionPerformed(evt);
            }
        });

        jButton_carslist.setBackground(new java.awt.Color(153, 153, 0));
        jButton_carslist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_carslist.setForeground(new java.awt.Color(255, 255, 255));
        jButton_carslist.setText("Cars List ");
        jButton_carslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_carslistActionPerformed(evt);
            }
        });

        jTextField_Class.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ClassMouseClicked(evt);
            }
        });

        jComboBox_brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBox_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_brandActionPerformed(evt);
            }
        });

        jComboBox_Fuel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Fuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasoline", "Diesel", "Petrol", "Hydro", "LPG", "Bioethanol", "CNG", "Biodiesel", "Propan", "Water", "Air", "Mist", "Solar", "Nitro", "Dynamic", "Amoniac", "Wood Gas", "Alcohol" }));

        jComboBox_Color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Color.setMaximumRowCount(8);
        jComboBox_Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White", "Black", "Red", "Yellow", "Green", "Blue", "Grey", "Brown", "Orange" }));

        jSpinner_passengers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Model.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Model.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ModelMouseClicked(evt);
            }
        });

        jSpinner_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jRadioButton_Automatic.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_Automatic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Automatic.setText("Automatic");

        jRadioButton_Manual.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_Manual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Manual.setText("Manual");
        jRadioButton_Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ManualActionPerformed(evt);
            }
        });

        jLabel_brand_id.setText("#");

        jButton_search.setBackground(new java.awt.Color(0, 0, 255));
        jButton_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        btn_undo_car.setBackground(new java.awt.Color(255, 255, 0));
        btn_undo_car.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_undo_car.setText("Undo");
        btn_undo_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_undo_carActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jSpinner_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_search))
                                    .addComponent(jComboBox_brand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_Model)
                                    .addComponent(jComboBox_Fuel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Color, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_brand_id, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner_price, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton_Automatic)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton_Manual))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Class, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner_passengers, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_add_car, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton_addcarimages, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(94, 94, 94)
                                    .addComponent(jButton_brandslist, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_carslist, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_undo_car, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField_Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_search)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jSpinner_passengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_brand_id)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton_Automatic)
                                .addComponent(jRadioButton_Manual))
                            .addComponent(jLabel11))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox_Fuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btn_undo_car, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_add_car, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addcarimages, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_brandslist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_carslist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jButton_add_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_carActionPerformed
        int car_id = (int) jSpinner_id.getValue();
        String brandIdText = jLabel_brand_id.getText();
        String model = jTextField_Model.getText();
        String fuel = jComboBox_Fuel.getSelectedItem().toString();
        String color = jComboBox_Color.getSelectedItem().toString(); 
        String _class_ = jTextField_Class.getText();
        int passengers = (int)jSpinner_passengers.getValue();
        String gearbox = "automatic";
        
        int price = (int)(jSpinner_price.getValue());
        
        String air_cond = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seates = "no";
        String nav_sys = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if (jRadioButton_Manual.isSelected()) { gearbox = "manual"; }
        
            if (jCheckBox_Features_AirCond.isSelected()) { air_cond = "yes"; }
                if (jCheckBox_Features_Airbags.isSelected()) { airbags = "yes"; }
                    if (jCheckBox_Features_Sunroof.isSelected()) { sunroof = "yes"; }
                        if (jCheckBox_Features_HeatedSeats.isSelected()) { heated_seates = "yes"; }
                            if (jCheckBox_Features_Bluetooth.isSelected()) { bluetooth = "yes"; }
                                if (jCheckBox_Features_NavigationSystems.isSelected()) { nav_sys = "yes"; }
                                    if (jCheckBox_Features_ElectricWindows.isSelected()) { elec_win = "yes"; }
                                        if (jCheckBox_Features_GPS.isSelected()) { gps = "yes"; }
                                        
        if(verify()){
            try {
                carsBus.addCar(car_id, Integer.parseInt(brandIdText), model, fuel, color, _class_, passengers, gearbox, price, air_cond, airbags, sunroof, heated_seates, nav_sys, bluetooth, elec_win, gps);
            } catch (Exception ex) {
                Logger.getLogger(Cars_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_add_carActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        int car_id = (int) jSpinner_id.getValue();
        int brand = Integer.valueOf(jLabel_brand_id.getText());
        String model = jTextField_Model.getText();
        String fuel = jComboBox_Fuel.getSelectedItem().toString();
        String color = jComboBox_Color.getSelectedItem().toString(); 
        String _class_ = jTextField_Class.getText();
        int passengers = (int)jSpinner_passengers.getValue();
        String gearbox = "automatic";
        
        int price = (int)(jSpinner_price.getValue());
        
        String air_cond = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seates = "no";
        String nav_sys = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if (jRadioButton_Manual.isSelected()) { gearbox = "manual"; }
        
            if (jCheckBox_Features_AirCond.isSelected()) { air_cond = "yes"; }
                if (jCheckBox_Features_Airbags.isSelected()) { airbags = "yes"; }
                    if (jCheckBox_Features_Sunroof.isSelected()) { sunroof = "yes"; }
                        if (jCheckBox_Features_HeatedSeats.isSelected()) { heated_seates = "yes"; }
                            if (jCheckBox_Features_Bluetooth.isSelected()) { bluetooth = "yes"; }
                                if (jCheckBox_Features_NavigationSystems.isSelected()) { nav_sys = "yes"; }
                                    if (jCheckBox_Features_ElectricWindows.isSelected()) { elec_win = "yes"; }
                                        if (jCheckBox_Features_GPS.isSelected()) { gps = "yes"; }
                                        
        if(verify()){
            try {
                carsBus.editCar(car_id, brand, model, fuel, color, _class_, passengers, gearbox, price, air_cond, airbags, sunroof, heated_seates, nav_sys, bluetooth, elec_win, gps);
            } catch (Exception ex) {
                Logger.getLogger(Cars_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        int car_id = (int) jSpinner_id.getValue();
        int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Delete this Car?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                carsBus.deleteCar(car_id);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        //Button to Reset all fields to there default value
        jSpinner_id.setValue(0);
        jTextField_Class.setText("");
        jTextField_Model.setText("");
        jSpinner_price.setValue(10);
        jLabel_brand_id.setText("#");
        jSpinner_passengers.setValue(2);
        jComboBox_Fuel.setSelectedIndex(0);
        jComboBox_Color.setSelectedIndex (0);
        jComboBox_brand.setSelectedIndex(0);
        jRadioButton_Automatic.setSelected(true);
        
        jCheckBox_Features_Airbags.setSelected(false);
        jCheckBox_Features_AirCond.setSelected(false);
        jCheckBox_Features_Bluetooth.setSelected(false);
        jCheckBox_Features_ElectricWindows.setSelected(false);
        jCheckBox_Features_GPS.setSelected(false);
        jCheckBox_Features_HeatedSeats.setSelected(false);
        jCheckBox_Features_NavigationSystems.setSelected(false);
        jCheckBox_Features_Sunroof.setSelected(false);
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_addcarimagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addcarimagesActionPerformed
        CarImages_GUI carimg_gui = new CarImages_GUI();
        carimg_gui.setVisible(true);
    }//GEN-LAST:event_jButton_addcarimagesActionPerformed

    private void jButton_brandslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_brandslistActionPerformed
        BrandsList_GUI brdlst_gui = new BrandsList_GUI();
        brdlst_gui.setVisible(true);
    }//GEN-LAST:event_jButton_brandslistActionPerformed

    private void jButton_carslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_carslistActionPerformed
        CarsList_GUI carlst_gui = new CarsList_GUI();
        carlst_gui.setVisible(true);
    }//GEN-LAST:event_jButton_carslistActionPerformed

    private void jComboBox_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_brandActionPerformed
        int brand_id = 0;
        for (Map.Entry<Integer, String> entry : map.entrySet())
        {
            if (entry.getValue().equals(jComboBox_brand.getSelectedItem().toString()))
            {
                brand_id = entry.getKey();
            }
        }
        jLabel_brand_id.setText(String.valueOf(brand_id));
    }//GEN-LAST:event_jComboBox_brandActionPerformed

    private void jRadioButton_ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_ManualActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        try {
            int car_id = (int) jSpinner_id.getValue();
            Cars_DTO new_car = carsBus.getCarById(car_id);

            jButton_resetActionPerformed(null);
            
            if (new_car != null) {
                jSpinner_id.setValue(car_id);
                jTextField_Class.setText(new_car.getClass_());
                jTextField_Model.setText(new_car.getModel());
                
                jSpinner_passengers.setValue(new_car.getPassengers());
                jSpinner_price.setValue(new_car.getPrice());

                jComboBox_brand.setSelectedItem(map.get(new_car.getBrand()));   
                System.out.println(map.get(new_car.getBrand()));
                jLabel_brand_id.setText(String.valueOf(new_car.getBrand()));
                
                jComboBox_Fuel.setSelectedItem(new_car.getFuel());
                jComboBox_Color.setSelectedItem(new_car.getColor());
                
                if(new_car.getGearbox().equals("manual")) {
                    jRadioButton_Manual.setSelected(true);
                }else {
                    jRadioButton_Automatic.setSelected(true);
                }
                System.out.println(new_car.getGearbox());
                
                if(new_car.getAir_cond().equals("yes")){jCheckBox_Features_AirCond.setSelected(true);}
                if(new_car.getAirbag().equals("yes")){jCheckBox_Features_Airbags.setSelected(true);}
                if(new_car.getBluetooth().equals("yes")){jCheckBox_Features_Bluetooth.setSelected(true);}
                if(new_car.getElec_window().equals("yes")){jCheckBox_Features_ElectricWindows.setSelected(true);}
                if(new_car.getGps().equals("yes")){jCheckBox_Features_GPS.setSelected(true);}
                if(new_car.getHeated_seats().equals("yes")){jCheckBox_Features_HeatedSeats.setSelected(true);}
                if(new_car.getNav_sys().equals("yes")){jCheckBox_Features_NavigationSystems.setSelected(true);}
                if(new_car.getSunroof().equals("yes")){jCheckBox_Features_Sunroof.setSelected(true);}   
            } else {
                ButtonGroup btn_group = new ButtonGroup();
                btn_group.add(jRadioButton_Automatic);
                btn_group.add(jRadioButton_Manual);
                btn_group.clearSelection();
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Cars_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jTextField_ModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ModelMouseClicked

    }//GEN-LAST:event_jTextField_ModelMouseClicked

    private void jTextField_ClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ClassMouseClicked

    }//GEN-LAST:event_jTextField_ClassMouseClicked

    private void btn_undo_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_undo_carActionPerformed
        try {
            Cars_DTO restoredCar = carsBus.undoDeleteCar();

            if (restoredCar != null) {
                carsBus.restoreCar(restoredCar);
                JOptionPane.showMessageDialog(this, "Car restored successfully!", "Undo Car", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "No car to restore.", "Undo", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error in undo operation: " + ex.getMessage(), "Undo Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_undo_carActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cars_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cars_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_undo_car;
    private javax.swing.JButton jButton_add_car;
    private javax.swing.JButton jButton_addcarimages;
    private javax.swing.JButton jButton_brandslist;
    private javax.swing.JButton jButton_carslist;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_search;
    private javax.swing.JCheckBox jCheckBox_Features_AirCond;
    private javax.swing.JCheckBox jCheckBox_Features_Airbags;
    private javax.swing.JCheckBox jCheckBox_Features_Bluetooth;
    private javax.swing.JCheckBox jCheckBox_Features_ElectricWindows;
    private javax.swing.JCheckBox jCheckBox_Features_GPS;
    private javax.swing.JCheckBox jCheckBox_Features_HeatedSeats;
    private javax.swing.JCheckBox jCheckBox_Features_NavigationSystems;
    private javax.swing.JCheckBox jCheckBox_Features_Sunroof;
    private javax.swing.JComboBox<String> jComboBox_Color;
    private javax.swing.JComboBox<String> jComboBox_Fuel;
    private javax.swing.JComboBox<String> jComboBox_brand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_brand_id;
    private javax.swing.JLabel jLabel_cars;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_imagePath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_Automatic;
    private javax.swing.JRadioButton jRadioButton_Manual;
    private javax.swing.JSpinner jSpinner_id;
    private javax.swing.JSpinner jSpinner_passengers;
    private javax.swing.JSpinner jSpinner_price;
    private javax.swing.JTextField jTextField_Class;
    private javax.swing.JTextField jTextField_Model;
    // End of variables declaration//GEN-END:variables
}
