/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CarImage_BUS;
import BUS.Cars_BUS;
import DTO.CarImage_DTO;
import DTO.Cars_DTO;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class CarsList_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CarsList_GUI
     */
    //the car id
    int carid;
    Cars_BUS carsBus = new Cars_BUS();
    ArrayList<Cars_DTO> cars_list = carsBus.getAllCars();
    
    CarImage_BUS carsimageBus = new CarImage_BUS();
    ArrayList<CarImage_DTO> carsimages;
    
    JLabel[] labels = new JLabel[6];
    //table of jlabels
    public CarsList_GUI() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        populateJTableWithCars();
        
        jTable_car.setRowHeight(40);
        labels [0] = jLabel_carimages_1;
        labels [1] = jLabel_carimages_2;
        labels [2] = jLabel_carimages_3;
        labels [3] = jLabel_carimages_4;
        labels [4] = jLabel_carimages_5;
        labels [5] = jLabel_carimages_6;
    }

    public void populateJTableWithCars() {
        ArrayList<Cars_DTO> cars_list = carsBus.getAllCars();
        //jtable columns
        String[] columnsName = {"ID", "Brand" , "Model", "Fuel", 
            "Color", "Class", "Passengers", "Gearbox", "Price", 
            "Air Conditioning", "AirBags", "Sunroof", "Heated Seats", 
            "Navigation Systems", "Bluetooth", "Electric Windows", "GPS"
        };
        
        // jtable rows
        Object[][] rows = new Object[cars_list.size()][columnsName.length];
        
        for(int i=0; i < cars_list.size(); i++)
        {
            rows[i][0] = cars_list.get(i).getCar_id();
            rows[i][1] = cars_list.get(i).getBrand();
            rows[i][2] = cars_list.get(i).getModel();
            rows[i][3] = cars_list.get(i).getFuel();
            rows[i][4] = cars_list.get(i).getColor();
            rows[i][5] = cars_list.get(i).getClass_();
            rows[i][6] = cars_list.get(i).getPassengers();
            rows[i][7] = cars_list.get(i).getGearbox();
            rows[i][8] = cars_list.get(i).getPrice();
            rows[i][9] = cars_list.get(i).getAir_cond();
            rows[i][10] = cars_list.get(i).getAirbag();
            rows[i][11] = cars_list.get(i).getSunroof();
            rows[i][12] = cars_list.get(i).getHeated_seats();
            rows[i][13] = cars_list.get(i).getNav_sys();
            rows[i][14] = cars_list.get(i).getBluetooth();
            rows[i][15] = cars_list.get(i).getElec_window();
            rows[i][16] = cars_list.get(i).getGps();
        }
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        jTable_car.setModel(model);
    }
    
    public void displayByteImage (int width, int height, byte[] image_byte, JLabel label)
    {
        // get the image
        ImageIcon imageIco = new ImageIcon(image_byte);
        // resize the image
        Image image = imageIco.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        // set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_car_list = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_car = new javax.swing.JTable();
        jLabel_car_image = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_carimages_1 = new javax.swing.JLabel();
        jLabel_carimages_2 = new javax.swing.JLabel();
        jLabel_carimages_3 = new javax.swing.JLabel();
        jLabel_carimages_4 = new javax.swing.JLabel();
        jLabel_carimages_5 = new javax.swing.JLabel();
        jLabel_carimages_6 = new javax.swing.JLabel();
        jButton_ShowSliderForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("All Cars");

        jLabel_car_list.setBackground(new java.awt.Color(255, 204, 0));
        jLabel_car_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        jLabel_car_list.setOpaque(true);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_car_list)
                .addGap(290, 290, 290)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_car_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable_car.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable_car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_car.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable_car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_carMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_car);
        jTable_car.setCellSelectionEnabled(false);
        jTable_car.setRowSelectionAllowed(true);
        jTable_car.setColumnSelectionAllowed(false);
        jTable_car.setDefaultEditor(Object.class, null);

        jLabel_car_image.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_car_image.setOpaque(true);

        jLabel_carimages_1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_carimages_1.setOpaque(true);

        jLabel_carimages_2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_carimages_2.setOpaque(true);

        jLabel_carimages_3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_carimages_3.setOpaque(true);

        jLabel_carimages_4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_carimages_4.setOpaque(true);

        jLabel_carimages_5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_carimages_5.setOpaque(true);

        jLabel_carimages_6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_carimages_6.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_carimages_4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_carimages_5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_carimages_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_carimages_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_carimages_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_carimages_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_carimages_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_carimages_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_carimages_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_carimages_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_carimages_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_carimages_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        jButton_ShowSliderForm.setBackground(new java.awt.Color(0, 0, 255));
        jButton_ShowSliderForm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ShowSliderForm.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ShowSliderForm.setText("Images Slider");
        jButton_ShowSliderForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowSliderFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_car_image, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ShowSliderForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_car_image, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ShowSliderForm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jTable_carMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_carMouseClicked
        //clear images
        jLabel_car_image.setIcon(null);
        
        for(int i = 0; i < labels.length; i++)
        {
            labels[i].setIcon(null);
        }
        // get the selected car image
        int index = jTable_car.getSelectedRow();
        int id = Integer.valueOf(jTable_car.getValueAt(index, 0).toString());// car id
        carid = id;//we need this to use it int the images slider form
        carsimages = carsimageBus.carImagesList(id);
        //display the images on the jlabels
        if(carsimages.size() > 0)
        {
            //get the first image
            displayByteImage(jLabel_car_image.getWidth(), jLabel_car_image.getHeight(), carsimages.get(0).getCar_img(), jLabel_car_image);
            
            for(int i=0; i < carsimages.size(); i++)
            {
                if(i < labels.length)
                    displayByteImage(labels[i].getWidth(), labels[i].getHeight(), carsimages.get(i).getCar_img(), labels[i]);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "This Car Has No Images", "No Image", 2);
        }
    }//GEN-LAST:event_jTable_carMouseClicked

    private void jButton_ShowSliderFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowSliderFormActionPerformed
        // show car images in a slider
        try{
            CarImages_Slider_GUI slider_gui = new CarImages_Slider_GUI(carid);
            slider_gui.setVisible(true);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "This Car Has No Images", "No Image", 2);
        }
        
    }//GEN-LAST:event_jButton_ShowSliderFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarsList_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarsList_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarsList_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarsList_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarsList_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ShowSliderForm;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_car_image;
    private javax.swing.JLabel jLabel_car_list;
    private javax.swing.JLabel jLabel_carimages_1;
    private javax.swing.JLabel jLabel_carimages_2;
    private javax.swing.JLabel jLabel_carimages_3;
    private javax.swing.JLabel jLabel_carimages_4;
    private javax.swing.JLabel jLabel_carimages_5;
    private javax.swing.JLabel jLabel_carimages_6;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_car;
    // End of variables declaration//GEN-END:variables
}
